general {
	hide_cursor = true
}

background {
	color = rgb(202020)
}

input-field {
	size = 200, 50
	outline_thickness = 2
	inner_color = rgb(303030)
	outer_color = rgb(909090)
	font_color = rgb(ffffff)
	placeholder_text = Contraseña...
	dots_size = 0.2
	dots_spacing = 0.2
	fade_on_empty = false
}
