monitor=,preferred,auto,1

env = XDG_CURRENT_DESKTOP,Sway

$terminal = kitty

exec-once = $terminal
exec-once = waybar
exec-once = swaybg -c  202020
exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprpolkitagent
exec-once = mako
exec-once = ~/.local/bin/lid-monitor-handler &

source = ~/.config/hypr/keybinds.conf

input {
	kb_layout = es,pl
	kb_options = grp:alt_shift_toggle
}

windowrule = float on, match:class ^(gsimplecal)$
