# Monitor configuration
monitor=eDP-1,1920x1080@144,0x0,1
monitor=HDMI-A-1,3440x1440@60,1920x0,1

env = XDG_CURRENT_DESKTOP,Sway

# NVIDIA-specific settings for stable multi-display rendering
env = NVIDIA_MIG_CONFIG,All-Disabled
env = __GL_SYNC_TO_VBLANK,1

$terminal = kitty

exec-once = $terminal
exec-once = waybar
exec-once = swaybg -c  202020
exec-once = hypridle
exec-once = hyprpaper
exec-once = hyprpolkitagent
exec-once = mako
exec-once = ~/.local/bin/lid-monitor-handler &

source = ~/.config/hypr/keybinds.conf

input {
	kb_layout = es,pl
	kb_options = grp:alt_shift_toggle
}

windowrule = float on, match:class ^(gsimplecal)$
