monitor=,preferred,auto,1

$terminal = kitty

exec-once = $terminal
exec-once = waybar
exec-once = swaybg -c  202020
exec-once = hypridle
exec-once = hyprpaper

source = ~/.config/hypr/keybinds.conf

input {
	kb_layout = es
}
